# 15:55 ~ 16:29
SELECT 
    DATE_FORMAT(A.SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
    PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM
(SELECT 
    SALES_DATE, 
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM ONLINE_SALE AS ONSALE
WHERE SALES_DATE LIKE "2022-03%"
UNION ALL
SELECT 
    SALES_DATE, 
    PRODUCT_ID,
    NULL USER_ID,
    SALES_AMOUNT
FROM OFFLINE_SALE AS ONSALE
WHERE SALES_DATE LIKE "2022-03%") AS A
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;