# -- 코드를 입력하세요
# # 9:26 ~ 10:04 
# SELECT
#     C.CAR_ID,
#     C.CAR_TYPE,
#     ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
#     # ,
#     # (100 - P.DISCOUNT_RATE) / 100
# FROM CAR_RENTAL_COMPANY_CAR AS C
# LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID
# LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON P.CAR_TYPE = C.CAR_TYPE
# WHERE C.CAR_ID NOT IN (
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01'
# ) AND P.DURATION_TYPE LIKE "30%" AND C.CAR_TYPE IN ("세단", "SUV")
# GROUP BY C.CAR_ID
# HAVING FEE >= 500000 AND FEE < 2000000
# ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;

#1. CAR_TYPE이 세단 OR SUV
#2. 2022년 11월 11일부터 11월 30일까지 대여 가능
#3. 한 달 대여 금액이 50 이상 200 미만인 자동차(한 달 대여하면 세단 10% 할인, SUV 8% 할인됨)
#4. CAR_ID, CAR_TYPE, FEE(정수만) 출력
#5. FEE DESC, CAR_TYPE ASC, CAR_ID DESC





#### 대리님 코드
SELECT RESULT.CAR_ID, RESULT.CAR_TYPE, RESULT.FEE
FROM (
    SELECT C.CAR_ID, C.CAR_TYPE,
        FLOOR(C.DAILY_FEE * 30 * (1 - COALESCE(P.DISCOUNT_RATE, 0) / 100)) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C LEFT JOIN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY CAR_ID
        HAVING MAX(END_DATE) < "2022-11-01"
    ) AS H ON C.CAR_ID = H.CAR_ID
    INNER JOIN (
        SELECT CAR_TYPE, DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE (CAR_TYPE = "세단" OR CAR_TYPE = "SUV")
            AND DURATION_TYPE = "30일 이상"
    ) AS P ON C.CAR_TYPE = P.CAR_TYPE
    WHERE H.CAR_ID IS NOT NULL
        AND (C.CAR_TYPE = "SUV" OR C.CAR_TYPE = "세단")
) AS RESULT
WHERE RESULT.FEE BETWEEN 500000 AND 1999999
ORDER BY RESULT.FEE DESC, RESULT.CAR_TYPE ASC, RESULT.CAR_ID DESC;