# 16:30
WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TIME
    WHERE HOUR < 23
)

SELECT 
    TIME.HOUR,
    COUNT(O.ANIMAL_ID) AS COUNT 
FROM TIME
LEFT JOIN ANIMAL_OUTS AS O ON HOUR(O.DATETIME) = TIME.HOUR
GROUP BY HOUR
ORDER BY HOUR