# # -- 코드를 입력하세요
# # SELECT 
# #     YEAR(SALES_DATE) AS YEAR,
# #     MONTH(SALES_DATE) AS MONTH,
# #     COUNT(I.USER_ID) AS PUCHASED_USERS
# # FROM USER_INFO AS I
# # LEFT JOIN ONLINE_SALE AS S ON I.USER_ID = S.USER_ID
# # WHERE JOINED LIKE "2021%"
# # GROUP BY I.USER_ID
# # ORDER BY YEAR, MONTH ASC;

# SELECT 
#     YEAR(SALES_DATE) AS YEAR,
#     MONTH(SALES_DATE) AS MONTH,
#     # COUNT(I.USER_ID) AS PUCHASED_USERS,
    
# FROM USER_INFO AS I
# INNER JOIN ONLINE_SALE AS S ON I.USER_ID = S.USER_ID
# WHERE I.USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE JOINED LIKE "2021%") 
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
# ORDER BY YEAR, MONTH ASC;

#1. 2021년에 가입한 전체 회원 조회
#2. 상품을 구매한 회원 조회 (PUCHASED_USERS)
#3. 구매 회원 / 전체 회원 = 비율 (PUCHASED_RATIO)

#1. 2021년에 가입한 회원
# SELECT 
#     *
# FROM USER_INFO AS I
# WHERE JOINED LIKE "2021%"

#2. 상품 구매한 회원
# SELECT *
# FROM ONLINE_SALE AS S
# INNER JOIN USER_INFO AS I ON S.USER_ID = I.USER_ID


#3. 2021년에 가입하고 상품 구매한 사람 => 이걸 카운트 세면 PUCHASED_USERS
# SELECT COUNT(*)
# FROM ONLINE_SALE AS S
# INNER JOIN USER_INFO AS I ON S.USER_ID = I.USER_ID
# WHERE I.JOINED LIKE "2021%"

#4.




# SELECT 
#     YEAR(SALES_DATE) AS YEAR,
#     MONTH(SALES_DATE) AS MONTH,
#     COUNT(DISTINCT S.USER_ID) AS PUCHASED_USERS,
#     ROUND(COUNT(DISTINCT S.USER_ID) / A.USER_COUNT, 1) AS PUCHASED_RATIO
# FROM (
#     SELECT COUNT(USER_ID) AS USER_COUNT
#     FROM USER_INFO
#     WHERE JOINED LIKE "2021%"
# ) AS A, ONLINE_SALE AS S
# INNER JOIN USER_INFO AS I ON S.USER_ID = I.USER_ID
# WHERE I.JOINED LIKE "2021%"
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH





SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) / T.TOTAL, 1) AS PUCHASED_RATIO
FROM (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) AS U INNER JOIN ONLINE_SALE AS S ON U.USER_ID = S.USER_ID
CROSS JOIN (SELECT COUNT(USER_ID) AS TOTAL FROM USER_INFO WHERE YEAR(JOINED) = 2021) AS T
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;