WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT E.ID, E.PARENT_ID, CTE.GENERATION + 1
    FROM ECOLI_DATA AS E
    INNER JOIN CTE ON E.PARENT_ID = CTE.ID
)
SELECT
    COUNT(CTE.ID) AS COUNT,
    CTE.GENERATION
FROM CTE
LEFT JOIN ECOLI_DATA AS C ON C.PARENT_ID = CTE.ID
WHERE C.PARENT_ID IS NULL
GROUP BY CTE.GENERATION