SELECT
    E1.ID,
    CASE
        WHEN PERCENT <= 25 THEN 'CRITICAL'
        WHEN PERCENT <= 50 THEN 'HIGH'
        WHEN PERCENT <= 75 THEN 'MEDIUM'
    ELSE 'LOW'
    END AS COLONY_NAME
FROM
    ECOLI_DATA AS E1
INNER JOIN (
        SELECT
            ID,
            PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) * 100 AS PERCENT
        FROM ECOLI_DATA
) AS A ON A.ID = E1.ID
ORDER BY ID