# -- 코드를 작성해주세요
# # 17:59 ~ 
# # SELECT
# #     D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
# # FROM DEVELOPERS AS D
# # LEFT JOIN SKILLCODES AS S ON D.SKILL_CODE = S.CODE
# # WHERE D.SKILL_CODE & b'100000000' + b'10000000000'
# # ORDER BY BINARY D.ID ASC;

# # SELECT b'1000' & b'1111' -- ==> 1000 ===> 2의 3제곱 ===> 8

# # SELECT
# #     D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
# # FROM DEVELOPERS AS D
# # LEFT JOIN SKILLCODES AS S ON D.SKILL_CODE = S.CODE
# # # WHERE D.SKILL_CODE & 256 OR D.SKILL_CODE & 1024
# # WHERE D.SKILL_CODE & b'100000000' OR b'10000000000'
# # ORDER BY BINARY D.ID ASC;


# SELECT
#     D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
# FROM DEVELOPERS AS D
# # LEFT JOIN SKILLCODES AS S ON D.SKILL_CODE = S.CODE
# WHERE D.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME IN("Python", "C#"))
# ORDER BY BINARY D.ID ASC;

# # SELECT SUM(CODE) FROM SKILLCODES WHERE NAME IN("Python", "C#")



SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS AS D
WHERE D.SKILL_CODE & ((SELECT CODE FROM SKILLCODES WHERE NAME = "Python") | (SELECT CODE FROM SKILLCODES WHERE NAME = "C#"))
ORDER BY BINARY D.ID ASC;