SELECT
    H.HISTORY_ID,
    FLOOR(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
        * 
    (CASE 
     WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 7 THEN 1
     WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 30 THEN 0.95
     WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 90 THEN 0.92
     ELSE 0.85 END)) AS FEE

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
INNER JOIN CAR_RENTAL_COMPANY_CAR AS C ON C.CAR_ID = H.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE = P.CAR_TYPE

WHERE C.CAR_TYPE = "트럭"
GROUP BY H.HISTORY_ID
ORDER BY FEE DESC, H.HISTORY_ID DESC;